name: One1Auth
version: 1.0
main: me.example.auth.AuthPlugin
api-version: '26.1'

commands:
  login:
    description: Login command
  register:
    description: Register command
  helpa:
    description: Manual
  hexgenerate:
    description: Generate hex random string
  vip:
    description: Become VIP command
  coupon:
    description: Coupon command
