services:
  cryecb:
    restart: unless-stopped
    image: cry-ecb
    build: ./source
    container_name: cry-easy-ecb
    ports:
      - "1447:1447"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2G
    volumes:
      - ./flag:/flag:ro