services:
  vstor_cache:
    build: .
    image: pwn-med-pathcache:latest
    privileged: true
    restart: unless-stopped
    ports:
      - "31337:31337"
    volumes:
      - ./image/vstor_cache.qcow2:/challenge/image/vstor_cache.qcow2:ro
    environment:
      QEMU_RAM: "2048"
      QEMU_SMP: "2"
