<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Message</AssemblyName>
    <RootNamespace>MessageLauncher</RootNamespace>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Launcher.Program.cs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="payload.zip">
      <LogicalName>payload.zip</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
</Project>
